### PR TITLE
Updated with Australian Locale

### PR DESCRIPTION
**Pull request by blind0wl**
Have updated smalltalk.py with en-AU...next edition I will probably just add it as a language with the en-US and en-DE variances.

### CODE REVIEW

**Comment by blind0wl** [comment]
The only thing I changed was en-US to en-AU..not sure how that could have broken it...

**Comment by YoSev** [comment]
It's your text editor..

**Comment by blind0wl** [comment]
Im wondering if someone can point me in the right direction to changing the code to include a third locale...so instead of me replacing en-US I can just add en-AU as a seperate language.  This can then be reflected to the plugin for everyone to download rather than just be for the AU locale and DE.

I used a mixture of vim and notepad++ to make the changes...the AU side of it all works for me...I cant say I've tested the DE side though.

**Comment by YoSev** [comment]
just add a third @register and use elif language == "your-Lang": to add replys..
no need to overwrite existing languages

**Comment by gugahoi** [comment]
agreed, should not overwrite US and you can just add a or in the US statement as the reply can be the same

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
