### PR TITLE
Lets Wolfram Answer All Questions That Other Plugins Do Not Pick Up. 

### PR DESCRIPTION
**Pull request by jztech101**

### CODE REVIEW

**Comment by macruler12** [comment]
so what does this exactly do differently then the current wolfram plugin?

**Comment by praetorians** [comment]
it answer all questions, as said above.
the current wolfram only respond to what is, when is etc.
for the unrecognized speech, usually, it will suggest websearch if it is not detected by the siri plugins.

using this one, it will answer all the query using wolfram, as long as wolfram recognized them.
otherwise, the exception will suggest websearch to you.

**Comment by macruler12** [comment]
ah i see, this shall be a pretty handy plugin then! 

i know this is way off topic for this part of the discussion.... but is there any texting plugins for this server currently?

**Comment by jztech101** [comment]
I should add that this pull request does not suggest a web search or do one for you as you should never put whole questions into google to get the best result.

**Comment by WebScript** [comment]
I think it is bad what you have done. Wolfram Alpha has 2000 queries limit. So when google speech translates "Call my Daddy" to "Something another" and the command does not exists it sends the query to the Wolfram Alpha server and then if it will not recognize it will return a WebSearch button. I think this should be done for WebSearch (what is done), but not for Wolfram Alpha. This is why I will not support this version. Any new versions from me will not include this Wolfram Alpha edit. Or I will edit it to use more WA keys. (Yes, it will increase the maximum queries.)

**Comment by jztech101** [comment]
How might one reach 2000 queries in one month I might ask?

**Comment by praetorians** [comment]
it depends on your daily usage and also the percentage of error speech recognized by the siri.
i am pretty sure not all of our intended speech is correctly recognized by siri, especially if english is not your native language. all un-recognized speech will then be throw to alpha. that will reduce your monthly query.

the query will be quicker drown if you are sharing the server to your friends / family.
then, the 66 queries per day to wolfram is really make sense to me ;)

**Comment by piejanssens** [comment]
Nice!

**Comment by jimmykane** [comment]
Hmm I got up to 2000 requests

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
