### PR TITLE
Added startup script for *buntu based systems

### PR DESCRIPTION
**Pull request by gugahoi**
Init.d script to have siriServer start on boot and as a service.

Instructions:
1. Copy the DaemonFiles/siriserver to /etc/init.d/siriserver
2. Edit the file with the PORT, USER and APPLICATION PATH related to your instalation
3. Make it executable
   
   sudo chmod a+x /etc/init.d/siriserver
4. Start the server:
   
   sudo service siriserver start
5. If all is well and you'd like it to start on boot just run
   
   sudo update-rc.d siriserver defaults
6. You are good to go! Other than 'start' command you can use 'stop' and 'restart'

Also, I only named the folder DaemonFiles because  @autobuck said he has an OS X script done and pending pull, however I believe the folder name should be changed to 'Startup Scripts' or something

### CODE REVIEW

**Comment by rbuckbailey** [comment]
Agreed, "Startup Scripts" is a much better cross-platform name.

**Comment by janrueth** [comment]
please fix commit to have a folder called startupScrips, name your startUpScript for the plattform you target and also add an instruction in the header of the file please

**Comment by rbuckbailey** [comment]
I figure that I should do the same, and I'm sorry to say I don't know enough about git to remove a bad commit, although I figure I can re-do it right easily enough. Can you give me a brief run-down? Otherwise I'll look it up and have it done maybe this afternoon/evening.

**Comment by gugahoi** [comment]
if you just do another commit to the same branch you made the pull request from, it should automatically be added to the merge.... It will show up in the page so you can check if it extended the pull request.

**Comment by rbuckbailey** [comment]
Thanks. I've updated mine. Note that I did use "startupScripts" with the T, assuming Eichhoernchen made a typo.

**Comment by janrueth** [comment]
@autobuck jup, typo, sry

**Comment by gugahoi** [comment]
i had not modified this yet.... oh well will have to make another pull request...

**Pull request merged**
