### PR TITLE
Alarm plugin

### PR DESCRIPTION
**Pull request by jmaroeder**
I know an alarm plugin was just pulled in earlier today - this is an alternate take that currently has more functionality - it allows changing alarms, more flexible speech, and specifying alarms in relative time (i.e., "wake me up in 8 hours.").

Not sure how to handle these sorts of situations, being relatively new to open source collaborative programming - if I'm stepping on toes, please let me know, and I'll gladly rename the plugin.

### CODE REVIEW

**Comment by AlphaBetaPhi** [comment]
I saw your early plugin when it was just basic structure and I had a working version. I'm not quite sure what happens in this case. I am currently working on listing alarms/deleting alarms, collab?

**Comment by atkr** [comment]
Thanks to both of you, both plugins work great :)

**Comment by janrueth** [comment]
I haven't had that situation either. Thats my first open source project as well, I think that it would be a good idea to rename it at first, remove both from plugins.conf and I will have a look at if it is possible to merge both plugins into one

**Comment by piejanssens** [comment]
Congratulations on the plugin in any way! ;-)

**Comment by jmaroeder** [comment]
@AlphaBetaPhi, have you gotten a chance to work on yours? I think the best thing moving forward would probably be for just one of us to try and incorporate the work of the other, and then continue working on it. I'd be happy to do this, but I won't get a chance to do so for another day or two. If you are able to do so earlier, then please let me know, and we can avoid duplicating any more work. :)

**Comment by janrueth** [comment]
I'm pretty busy with other stuff, I think I won't be able to merge this either... I would be glad if you two would be able to get the best out of both and do a pull request if done...

**Comment by AlphaBetaPhi** [comment]
@jamesmallen I would be able to merge the plugins and submit a pull. I have worked on the plugin to add the ability to list and delete alarms. I'm currently sorting out reminder objects so that when a user requests an alarm to be set in the future it will create a reminder instead.

**Comment by jmaroeder** [comment]
@AlphaBetaPhi sounds good. I'll close this pull request and let you finish things up!

**Comment by jmaroeder** [comment]
@AlphaBetaPhi I was planning on doing reminders next too. :) If you've got it covered, though, I'll try to figure out something else to do!

**Pull request closed without merging**
