### PR TITLE
Add force language option

### PR DESCRIPTION
**Pull request by mshima**
I want to use SiriServer with pt-BR but Siri does not have this option so this option will force SiriServer to run using this language.

### CODE REVIEW

**Comment by edsonaj** [comment]
https://github.com/edsonaj/SiriServer

**Comment by janrueth** [comment]
Hm, actually the server supports multiple users, I don't see why one should want to force a single language for all participants...

**Comment by praetorians** [comment]
the server can only hear from one language. from my previously trial, if i don't change the self.assistant.language = "xx-XX" on siriServer.py, the siri couldn't hear my native language. even though i already have add all the @register to support my native language.

based on that, could we make an assumption that the siri server is only support one language ?

ATM, everytime i wanna change my siri language, i need to rename the plugins folder and also plugins.conf then run the siriserver.py.

**Comment by edsonaj** [comment]
It only supports one language if this language is not supported by Siri and you have to manual force it.

**Comment by janrueth** [comment]
No, the server supports the languages you select in siri on the iPhone, so it can recognize different languages for different users, to force a certain language for all user's is not the correct way I think, there should be a siri patch that lets you select more languages instead of patching the server

**Comment by edsonaj** [comment]
If all users use the same language I don't think that, and patching Siri is very complicated comparing to just patch the server.
Now if you want multiple users with different languages AND "not-supported" languages you should patch Siri, just make sure that, in case of a 4s, you don't make Siri to stop working with Apple Servers.
Before anyone tell me why someone would use the server with a 4s, for the non-supported languages.

**Comment by DigitalJosee** [comment]
I found a method, in httpclient.py change url on line 22 to:
https://www.google.com/speech-api/v1/recognize?xjerr=1&client=speech2text&lang=pt-BR&maxresults=10
Siri is now recognizing portuguese, now change plugins.

**Comment by edsonaj** [comment]
Get my fork, its working in portuguese.
If you change just there in the plugins you have to put the language from siri (en-US) for example. In mine you have to put pt-BR, and I changed some default speechs too.

**Comment by DigitalJosee** [comment]
I did the same thing, already translated most of the plugins

**Comment by mshima** [comment]
Eichhoernchen:
It would be much better, but until someone finds how it can be done, this workaround works, and passing as a command line option is much better then changing in code every time I want to switch between languages.

Seems that right now there are at least 3 persons working on pt-BR support for SiriServer: edsonaj, DigitalJosee and myself.
I have patches for pt-BR support. If you think it's a good idea to merge then I will propose.

**Comment by edsonaj** [comment]
Any of you already translated Wolfram plugin or the Notes plugin? As soon as I finish my plugins for my home automation I will starting translating some.....

**Comment by WebScript** [comment]
edsonaj wait for few days and I will release automatic translated version of Wolfram Alpha to all languages.

How can I check if Slovak language is working with Google Speech API? Or what is the language shortcut that uses speech api? (xy-XZ)

**Comment by edsonaj** [comment]
You have to use lang-COUNTRY.... I know that Slovak is sk, so is sk-COUNTRYCODE.
Here is a list of the language codes: http://code.google.com/apis/language/translate/v1/getting_started.html#detectResult

**Comment by edsonaj** [comment]
Well, I modified the Notes plugin and it's working in pt-BR: https://gist.github.com/1771902

**Comment by DigitalJosee** [comment]
I altered the time plugin for portuguese:
Comands:
Show hour:"._horas._"
Show world hour:"._Horas._em"
Link: https://github.com/downloads/DigitalJosee/SiriServer/time.py

Weather plugin portuguese:
Comands:
Weather:"._Tempo._"
World Weather:"._Tempo._em.*"
link:http://cloud.github.com/downloads/DigitalJosee/SiriServer/weather.py

**Comment by edsonaj** [comment]
I had to modify the time to make it work here, but the weather I couldn't get it working, it gives an error:
ascii enconder can't.... u'\xc3' in position 1.

Will try to fix it asap

**Comment by DigitalJosee** [comment]
Truco Joke:
You: Truco.*
Siri:Seis,Marreco!
You:Nove.*
Siri:Doze

Link: https://github.com/downloads/DigitalJosee/SiriServer/Truco.py

**Comment by edsonaj** [comment]
kkkk awesome :p

**Comment by WebScript** [comment]
I tried sudo python siriServer.py --lang sk-SK and it translates in English. What I am doing wrong?

**Comment by WebScript** [comment]
It works well with Czech language.

**Comment by edsonaj** [comment]
Are you sure that the code is sk-SK?

Edson Alves Junior
Star Center Soluções em Climatização LTDA

**Comment by WebScript** [comment]
I am not sure. But I read in some magazine that Google Chrome Speech does not support Slovak. (I don't know how old is this information.)

**Comment by fbloise** [comment]
Any help setting this up for Latin america spanish (mexican regional accent will be OK since is the most neutral of all).

**Comment by edsonaj** [comment]
Modify my repo changing every pt-BR you find (root dir) to es-AR (Argentina, I don't know the Mexico code), and create the plugins.

**Comment by fbloise** [comment]
thanks edsonaj

**Comment by keerttttt** [comment]
Let's implement this! :) looks like a good idea. But maybe it would be good to make a config file where all settings like this (and api keys e.g.) should be stored and loaded?

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
