### PR TITLE
Hi, this is the last and stable pull request  :-)

### PR DESCRIPTION
**Pull request by jimmykane**
Hi there, 

I would like to contribute to your project as much as i can. 

See some changes in my pull request, and no need to change to mysql, just see the changes such as: 

-fixed if user language or anything from info was not detected,
-added user name or nickname functions and plugin support
-fixed sqlite descriptor (switched to mysql)

### CODE REVIEW

**Comment by jimmykane** [comment]
@Eichhoernchen Please look at the siriServer.py and plugins.py to the changes for user firstname and nickname recognition. 
You can easily adopt it to sqlite!

**Comment by chickentw** [comment]
I had install python-mysql and everything but when I test it just stop on decoding

INFO read_next_object_from_unzipped Received a Ping (1)
INFO read_next_object_from_unzipped Returning a Pong (1)
INFO read_next_object_from_unzipped Received a Ping (2)
INFO read_next_object_from_unzipped Returning a Pong (2)
INFO read_next_object_from_unzipped Received a Ping (3)
INFO read_next_object_from_unzipped Returning a Pong (3)
INFO read_next_object_from_unzipped Received a Ping (4)
INFO read_next_object_from_unzipped Returning a Pong (4)
INFO process_compressed_data New start of speech received
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet
INFO process_compressed_data Decoding speech packet

**Comment by jimmykane** [comment]
@doratown this may happen on some requests that google fails to recognize

**Comment by snxraven** [comment]
@jimmykane did you fix this issue with mysql support?

http://grwh.net/error.PNG

**Comment by jimmykane** [comment]
Try it, Changed some descriptors etc. 
Keep me posted!

**Comment by snxraven** [comment]
@jimmykane I applied your latest files, i had to revert got this error for every connection:

error: uncaptured python exception, closing channel <**main**.HandleConnection connected 50.9.215.131:50818 at 0x1cf83368> (<type 'exceptions.KeyError'>:'firstName' [/usr/local/lib/python2.7/asyncore.py|read|83] [/root/server/sslDispatcher.py|handle_read_event|77] [/usr/local/lib/python2.7/asyncore.py|handle_read_event|442] [siriServer.py|handle_read|116] [siriServer.py|process_compressed_data|382])

**Comment by jimmykane** [comment]
? did you put the certs back?  and deleted the old tables ?

**Comment by snxraven** [comment]
I just tried emptying the tables and testing it, the no language error shows up in console and turning siri on/off is not working , so I had to re-upload the db backup, i had to revert back so my users can still connect

**Comment by jimmykane** [comment]
hmm interesting... didnt have that for a public server that i test. 
Delete all tables etc? Can you try that at a home server?

**Comment by jimmykane** [comment]
So after the db backup it works ok?

**Comment by snxraven** [comment]
Not the new commit, the db backup only works with the old commit

**Comment by jimmykane** [comment]
I think I found the bug. I am not home ATM but will fix by tomorrow. Thanks.

**Comment by snxraven** [comment]
Thank you sir, will be waiting :)

**Comment by jimmykane** [comment]
@snxraven Try this.... is it ok? Thanks for your feedback

**Comment by snxraven** [comment]
@jimmykane made a test server with your newest updates just now, i still get: Unable to find language record for this assistant. Try turning Siri off and then back on.

**Comment by gavros** [comment]
Same thing is happening to me as well.

**Comment by jimmykane** [comment]
I finally fixed the bug! Sorry it was my mistake. The db.py did not create all the table columns. Must have been mixed with some other version . 

Sorry guyz! 

Need some testers to confirm this is ok!

**Comment by boeaja** [comment]
latest version work for me.... before chatbot ... i have it already
btw you might need to put wolfram at the bottom of plugin.conf

i try "horoscope for scorpio" it handle by wolfram plugin, after i put wolfram at the bottom its load horoscope plugin

**Comment by gavros** [comment]
def put wolfram at the bottom of the plugin.conf ;)

**Comment by snxraven** [comment]
@jimmykane Good job fixing that, your changes are now live at:
http://siri.grwh.net/

WORKING PERFECTLY

**Comment by snxraven** [comment]
@jimmykane Server just shut down on me again: 
Traceback (most recent call last):
  File "siriServer.py", line 532, in <module>
    asyncore.loop()
  File "/usr/local/lib/python2.7/asyncore.py", line 214, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 144, in poll
    r, w, e = select.select(r, w, e, timeout)
select.error: (9, 'Bad file descriptor')

**Comment by jimmykane** [comment]
@snxraven hmm when you say crash do you mean whole server shutdown or only the connection of the device dropped? 

@boeaja I have modified the horoscope plugin and now it doesnt interfere with wolf! 
I changed whats the horoscope to tell me the horoscope mpla mpla

**Comment by Playfrog4u** [comment]
```
self.handle_read_event()
```

  File "/root/Google/1.5/Install-Siri/SiriServer/sslDispatcher.py", line 77, in handle_read_event
    asyncore.dispatcher_with_send.handle_read_event(self)
  File "/usr/lib/python2.7/asyncore.py", line 438, in handle_read_event
    self.handle_read()
  File "siriServer.py", line 116, in handle_read
    self.process_compressed_data()
  File "siriServer.py", line 206, in process_compressed_data
    reqObject = self.read_next_object_from_unzipped()
  File "siriServer.py", line 430, in read_next_object_from_unzipped
    return self.parse_object(object_data)
  File "siriServer.py", line 434, in parse_object
    plist = biplist.readPlistFromString(object_data)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 117, in readPlistFromString
    return readPlist(StringIO(data))
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 91, in readPlist
    result = reader.parse()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 152, in parse
    return self.readRoot()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 184, in readRoot
    result = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 247, in readObject
    result = self.readArray(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 297, in readArray
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 247, in readObject
    result = self.readArray(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 297, in readArray
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 228, in readObject
    result = self.readDate()
  File "/usr/local/lib/python2.7/dist-packages/biplist-0.4-py2.7.egg/biplist/**init**.py", line 331, in readDate
    result = datetime.datetime.utcfromtimestamp(result + apple_reference_date_offset)
ValueError: timestamp out of range for platform time_t

Some of code when crashed

**Comment by jimmykane** [comment]
@Playfrog4u This must be due to your system config!ValueError: timestamp out of range for platform time_t

**Comment by Playfrog4u** [comment]
Can I fix it?

**Comment by snxraven** [comment]
@jimmykane the server stops responding to clients and freezes cnt even close it properly i have to kill the procreess

**Comment by Playfrog4u** [comment]
Is there going to be a fix?

**Comment by snxraven** [comment]
@jimmykane  Do you know what would do that?

**Comment by jimmykane** [comment]
@snxraven  no to be honest no! I suppose that the os is doing that! 
I suppose only! I am new to python. 
But I am running this on paradox-productions.net with more than 100 connections and its working without crashes. My OS is gentoo. 

Any info and feedback is appropriated!

**Comment by snxraven** [comment]
@jimmykane idk anything about python but this may help you: http://bytes.com/topic/python/answers/589612-asyncore-select-statement-problem

**Comment by jimmykane** [comment]
I think that the asyncore.loop(use_poll = True) will fix this! 

Will make some test and keep you posted @snxraven 

Thanks for the info!

**Comment by jimmykane** [comment]
@snxraven I this this may fix the descriptor problem. 

As I read in the article and studied a little more the code the asyncronous.loop doesnt close the descriptors (using select) and so the system runs out of them (system dependand) thus stalling both server and python. 

Made the epoll change and now should work great! 

Keep me posted!

**Comment by chickentw** [comment]
Cool it works...But When I try to make it reply random it does not work

mycode: http://pastebin.com/pLyvswXs

I also try to put .format(self.user_name()) behind every reply but it get error...

**Comment by snxraven** [comment]
I added, asyncore.loop(use_poll = True) we will test it, 701 users

**Comment by boeaja** [comment]
http://docs.python.org/library/asyncore.html

**Comment by snxraven** [comment]
@jimmykane I am still receiving crashes, just an update

**Comment by jimmykane** [comment]
@snxraven if its ssl its ok for now ! is it db related please post output

**Comment by jimmykane** [comment]
@snxraven Also try the latest, switched to 1 db connection from many

**Comment by snxraven** [comment]
Installing now, Will post in a sec

**Comment by snxraven** [comment]
@jimmykane So Far, its working, crashes tend to happen after like 3-5 hours will post back in a bit

**Comment by jimmykane** [comment]
Ok. Keep me posted about major crashes (these that stall the server) and those that are not ssl related (looking into this also) 
This version "ok tested" is running so far so good.

**Comment by snxraven** [comment]
859 Users and still stable! Hoping it will keep up

**Comment by snxraven** [comment]
1,263 users, here is the error i got on crash:

 if obj.readable():
  File "siriServer.py", line 84, in readable
    self.handle_read_event()
  File "/root/server/sslDispatcher.py", line 77, in handle_read_event
    asyncore.dispatcher_with_send.handle_read_event(self)
  File "/usr/local/lib/python2.7/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "siriServer.py", line 115, in handle_read
    self.process_compressed_data()
  File "siriServer.py", line 358, in process_compressed_data
    c.execute("UPDATE `assistants` set censorSpeech=%s,timeZoneId=%s,language=%s,region=%s,firstName=%s,nickName=%s  where assistantId = %s", (self.assistant.censorSpeech,self.assistant.timeZoneId, self.assistant.language,self.assistant.region,self.assistant.firstName,self.assistant.nickName,self.assistant.assistantId))
  File "/usr/local/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 159, in execute
  File "/usr/local/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 264, in literal
  File "/usr/local/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 202, in unicode_literal
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

**Comment by snxraven** [comment]
@jimmykane Traceback (most recent call last):
  File "siriServer.py", line 535, in <module>
    asyncore.loop(use_poll = True)
  File "/usr/local/lib/python2.7/asyncore.py", line 214, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 180, in poll2
    if obj.readable():
  File "siriServer.py", line 84, in readable
    self.handle_read_event()
  File "/root/server/sslDispatcher.py", line 77, in handle_read_event
    asyncore.dispatcher_with_send.handle_read_event(self)
  File "/usr/local/lib/python2.7/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "siriServer.py", line 115, in handle_read
    self.process_compressed_data()
  File "siriServer.py", line 262, in process_compressed_data
    (decoder, encoder, dictation) = self.speech[speechPacket.refId]
KeyError: 'B262B720-5E46-4B5B-9329-B80B1A67CD4A'

**Comment by jimmykane** [comment]
So it's now a bit more stable except the username error. 

The key error must not affect runtime as i can imagine! 

Let me fix the mysql error

**Comment by jimmykane** [comment]
I added some unicode support! 

This should fix many issues! 

@snxraven  Is the database you created utf8 ? 
because i can see here that the connection is UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

**Comment by snxraven** [comment]
utf8_general_ci

**Comment by jimmykane** [comment]
ok let me investigate. Working with a chinese user to handle this encoding chaos

**Comment by snxraven** [comment]
Thank you!

**Comment by jimmykane** [comment]
The fact is that UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)
has something to do with the databse or the database connection, 

I have tested this on my db + connection with Chinese name etc (it crashed with this on another server) and mine seems ok.

Just reporting here. I will investigate more!

**Comment by snxraven** [comment]
Thanks for looking into it, cant wait for patch

**Comment by jimmykane** [comment]
Tha maximum user number is ok e?

**Comment by snxraven** [comment]
What is the max level? im at 2,097 users logged into DB

**Comment by jimmykane** [comment]
hehe nice. This means that epoll works great

**Comment by snxraven** [comment]
Yea, we got it workin well! Just need DB working properly :(

**Comment by jimmykane** [comment]
Try this version and report. Everything should be fixed. If you want disable the yelp plugin

**Comment by snxraven** [comment]
@jimmykane Added current git to my server, Test started

**Comment by jimmykane** [comment]
Excellent!

**Comment by snxraven** [comment]
@JimmyKane: 

Traceback (most recent call last):
  File "siriServer.py", line 538, in <module>
    asyncore.loop(use_poll = True)
  File "/usr/local/lib/python2.7/asyncore.py", line 214, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 180, in poll2
    if obj.readable():
  File "siriServer.py", line 87, in readable
    self.handle_read_event()
  File "/root/server/sslDispatcher.py", line 77, in handle_read_event
    asyncore.dispatcher_with_send.handle_read_event(self)
  File "/usr/local/lib/python2.7/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "siriServer.py", line 118, in handle_read
    self.process_compressed_data()
  File "siriServer.py", line 207, in process_compressed_data
    while self.hasNextObj():
  File "siriServer.py", line 409, in hasNextObj
    cmd, data = struct.unpack('>BI', self.unzipped_input[:5])
struct.error: unpack requires a string argument of length 5

**Comment by jimmykane** [comment]
And total server stall? This is not a db issue (just noting).

**Comment by snxraven** [comment]
Yes, the entire server stalled out must kill pid and restart, I split the load by 2 nd running 2 ports now

**Comment by jimmykane** [comment]
Ok. How many connections?

cmd, data = struct.unpack('>BI', self.unzipped_input[:5])
struct.error: unpack requires a string argument of length 5

will try to escape this for not to happen

**Comment by snxraven** [comment]
2,515

**Comment by jimmykane** [comment]
keep me posted on other stalls! I hope the mysql is fixed!

**Comment by jimmykane** [comment]
@snxraven I see in this thread (http://www.groupsrv.com/computers/about258113.html) that this must be due to some Os systems regarding your latest error. 

try one of the following and report if the error persists: 
check your system max number of file descriptors: 
ulimit -a 

and try increasing that to bigger values like

ulimit -n 2048 or even bigger. 

Also check if you are not our of memory!

**Comment by jimmykane** [comment]
So to sum up for @Eichhoernchen ! 

-Added SQLite support for multiple threads! 
-added MySQL support
- Added safe Unicode first name and nickname recognition 
- added first name and nickname plugin support 
- Added poll(2) for asyncore. That can hold up to many many connections (depends on os)
- improved the no language error with new assistant creation
- Some bug fixes and performance improvements 
- added French support to errors and smaltalk 
- new plugins -imbdb,yelp search and horoscope and chatbot
  -some other things that I might be missin 

Ps. As of now it looks very stable. Uptime on server with 3,5k users (gentoo) 24 hours and increasing.

**Comment by jimmykane** [comment]
Btw and last troll, I am using SQLite for all those connections.

**Comment by snxraven** [comment]
What would you think would b best sqlite or mysql?

**Comment by jimmykane** [comment]
Each has pros and cons. 
MySQL is more stable and has more performance while SQLite is more lightweight. 
Some 2 key features in my opinion. 
Try the SQLite for a change.

**Comment by jimmykane** [comment]
Also check at the info I posted about your crash

**Comment by snxraven** [comment]
@JimmyKane its been up all day! Thank you so much

**Comment by janrueth** [comment]
Uff looks like a lot of stuff I have to go through when I get back home

**Comment by jimmykane** [comment]
I can make only the essential changes as a pull request and get rid the plugins. 
If you like ignore the plugin updates an just look at the siriserver.py, db.py and plugin.py. 
This is where most of the changes here made. 
These files are tested for 5 days uptime an over 1000+ users 
Also I switched to SQLite and performance is good. 
Most bugs are resolved.

**Comment by jimmykane** [comment]
Also I am willing to explain and collab on any platform you like or solve any question ("including the meaning of life") 
Juts jokin. I also speak German a bit so no problem with German too

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
