### PR TITLE
adding alarm plugin, timer objects, and other minor edits

### PR DESCRIPTION
**Pull request by jmaroeder**
These changes mostly involve the addition of timer objects and the ability to set timers using the timer plugin. There are some issues with some of the timer commands - for some reason, the plugin isn't calling all of them. Also, some of the commands can cause the SpringBoard to crash, but basic functionality is working.

There are also a few other minor edits, including:
- renaming the time.py plugin to timePlugin.py
- adding a --logfile parameter to the startup options
- modifying AssistantUtteranceView to automatically use the speakableText as the text parameter if text is not given

### CODE REVIEW

**Comment by seabass86** [comment]
some of the timer functions cause the springboard to crash... should not be pulled until fixed.

**Comment by janrueth** [comment]
I agree, won't pull until spring isn't crashing

**Comment by DerPeiler** [comment]
translate also to German please! ;-)

**Comment by instipod** [comment]
Showing the timer still causes a springboard crash

**Comment by rbuckbailey** [comment]
I'd love to test this out but I'm getting "I don't understand Set alarm for 1 hour" and such errors. Am I using the wrong language or is the problem someplace else?

I do have parsedatetime installed and see no conspicuous errors in either system log, server or client.

**Comment by jmaroeder** [comment]
All right, no more springboard crashes that I can find, I think it's primed for someone to add German translations, and I fixed my dumb mistake with some of the hooks not coming through (darn copy and pasted code).

@autobuck, you actually don't need parsedatetime any more. The problem is that this currently only sets timers, not alarms. You can do "set timer for 1 hour" at the moment. Alarms are next on my todo list. :-)

**Comment by rbuckbailey** [comment]
@jamesmallen "set timer for 1 hour" gives me the same "I don't understand" error. Tried moving it up in the plugins.conf load list; haven't tried removing others, yet.

**Comment by jmaroeder** [comment]
@autobuck did you just copy the alarm.py file into a working setup? I've made a change to siriObjects/uiObjects.py that needs to be pulled as well, and also the file siriObjects/timerObjects.py is necessary. Not sure if it would be better to include that in the plugin file or not, but I figured since that was a standard Siri thing it'd be nice for other plugins to be able to use it.

**Comment by rbuckbailey** [comment]
Yeeees, I might have half-assed the install. I didn't want to break the modifications I had made by trying a proper pull and I missed stuff. Thanks! Going to grab those two files as well now.

**Comment by rbuckbailey** [comment]
Resprings on "show timer." Sorry. :)

Here is a pastie.org link to my syslog at the time of the crash, for what it's worth:

http://www.pastie.org/3331731

**Comment by jmaroeder** [comment]
@autobuck Are you using the complete code from 4aa203f?

**Comment by rbuckbailey** [comment]
I am. I was quite sure I was, but I double checked clicking through your link there, reinstalled it, and still get the crash.

**Comment by jmaroeder** [comment]
@autobuck Do other parts of it work? Can you try running python siriServer.py -l debug and share the debug messages from siriServer leading up to that?

**Comment by rbuckbailey** [comment]
Here's where it hung: http://www.pastie.org/3331785

After it opened up in safe mode, I got a ping-pong return.

Setting timers works fine, and it displays the timer at the time it sets it. The timer is still counting down, in fact, from that first test.  37 minutes left. Is there any other functionality I could test?

**Comment by jmaroeder** [comment]
okay, that looks like it's double-wrapping the AssistantUtteranceView (line 94 of your pastie). This was fixed in aaba91b01c880c3e1f488ee75b462c32928af0a0 line 230. Can you double-check line 230 of your alarm.py and make sure that there are not square brackets around AssistantUtteranceView? If you continue to have trouble, it might be best to open up an issue in my repo rather than cluttering this pull request...

**Comment by rbuckbailey** [comment]
Oh boy, I've tracked this one down. Comedy of errors.

alarm.py was correct.. but, alpha.py was the old, bad alarm.py. Because I made a terrible typing mistake at some point.

Now that I've restored my alpha.py plugin, it's not overlapping with the real alarm, and everything works fine. Sorry... my bad.

**Comment by janrueth** [comment]
very good commit, thank you

**Pull request merged**
