### PR TITLE
Some default snippets, objects, and commands

### PR DESCRIPTION
**Pull request by cale250**
Lots of objects for plugins to use in the future. This is by no means complete, as I will add more as I come across them.

This should be merged before Bubelbub's code, as he changed the top half of the uiObjects.py file.

### CODE REVIEW

**Comment by cale250** [comment]
I can see I pulled a rather dumb thing and forgot to add the refId parameter to each and every ClientBoundCommand, of which you had to fix. My apologies.

**Comment by janrueth** [comment]
No problem, I should have checked more careful before merging...

**Comment by cale250** [comment]
Be careful with changing some of them to commands versus the AceObjects. Check your e-mail - I sent you the portion of the log I based my code from.

**Comment by janrueth** [comment]
Do you refer to SendCommands?

From the header dump I made from siriframework I got:

@interface SASendCommands : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray\* commands;
- (id)sendCommands;
- (id)sendCommandsWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
  @end

**Comment by cale250** [comment]
I used SiriProxy with the debug level set to 9 to get actual communications. Here's a portion of what came from Guzzoni:
http://pastebin.com/0vSajdf3

I think the SendCommands you're referring to is different from the one used there.

**Pull request merged**
