### PR TITLE
Added Wolfram Alpha and Notes plugin

### PR DESCRIPTION
**Pull request by piejanssens**
also merged daemonfiles into startupscripts (duplicate purpose) + cleanup

### CODE REVIEW

**Comment by piejanssens** [comment]
@Eichhoernchen Whatsup, don't like pulling today? :p

**Comment by WebScript** [comment]
Edited: MERGE THIS IF YOU WANT. I WILL BE HAPPY TO SEE WOLFRAM ALPHA IN MAIN SIRISERVER.

**Comment by gugahoi** [comment]
sweet, good thing you changed to startupScripts! I was gonna do that later....

**Comment by WebScript** [comment]
If Wolfram does not find your query this edited script will get your iPhone into Safe Mode.

**Comment by piejanssens** [comment]
This script worked fine for me... And there was a bug before edit, that's why it's edited.

**Comment by WebScript** [comment]
Can you post the info about the bug? Because this is an old buggy version :P.

**Comment by WebScript** [comment]
Sorry but this I have changed yesterday. Probably you have old version. Can you edit code in this merge (Wolfram Alpha plugin) with this new? http://pastebin.com/n1Grdn5Y

**Comment by piejanssens** [comment]
@WebScript Could you please remove your big capitalized comments about not merging this?

Btw, may I ask, why are you not forking and contributing that way?

**Comment by WebScript** [comment]
Because I don't have time to setup own fork. I will do this ASAP.

**Comment by WebScript** [comment]
Edited the comment

**Comment by piejanssens** [comment]
Ok thanks, if you need help to setup your own fork. Contact me on #SiriServer on Freenode IRC.
I'd love to see some more plugins from you, especially SMS/calls and Mails.

**Comment by WebScript** [comment]
Thank you. But I don't like building plists for responses. I will try to create something with the actual snippets.
I have created my own fork :).

**Comment by janrueth** [comment]
Calm down^^ This is just a hobby for me.. I got other stuff to do the rest of the day...

**Pull request merged**
