### PR TITLE
Added external libraries

### PR DESCRIPTION
**Pull request by gugahoi**
Added:

```
M2Crypto
biplist
jsonrpclib (XBMC plugin)
```

All of them are in the 'lib' folder. This eliminates the need to have the user install them on their computer (hopefully) ...
I have only tested on Mac OS X after deleting all 3 from my system, the server still ran fine. Have not checked if I need to install their dependencies too (probably do) but if other people could test on their system and give some feedback it would be great! Ideally, we can have all the dependencies we need here (including libflac and libspeex) and have full control over which version is in. Eliminating headache for both the user and developer (I can see the amount of issues regarding installation)

### CODE REVIEW

**Comment by gugahoi** [comment]
This has to be on hold for now as the libraries do not seem to be cross platform. Will research a bit more...

**Comment by gugahoi** [comment]
M2Crypto seems to have the need to be compiled on a system specific basis so could not be included here. However this still makes installation easier since we can skip the step

```
easy_install biplist
```

with the added bonus of having jsonrpclib in which in turn makes the XBMC plugin work. Other python only dependencies can be added in the future if necessary...

**Comment by janrueth** [comment]
Yeah, I don't know, also there are so many possible platforms which libraries should run on. I would suggest to create an installation script, that loads all necessary dependencies and installs them, instead of providing all libraries on it's own. We could also eliminate typical errors like having an SSE2 optimized libspeex on the system

**Comment by gugahoi** [comment]
Hmmm, ye a script would be good, but this still minimizes any issues that may come about with installation....

**Comment by gugahoi** [comment]
@Eichhoernchen -> don't want to be annoying but is there a reason why you don't what this?

**Comment by janrueth** [comment]
Yes, I don't think it is a good idea to have external libraries together with a binary, they should be useable for the whole system, thats basically the whole idea of shared libraries. Also some need to be compiled for the target system

**Comment by gugahoi** [comment]
I understand those, but how about platform independent libraries like biplist and jsonrpc?

**Comment by m404** [comment]
you still miss his point of "that's not the point of shared libraries".

shared libraries are supposed to be installed on a system to be used by whatever binary wants to make use of them, not included in a "proprietary" location included with a single application ... if you "install" the SiriServer, u get (in ur case) biplist and jsonrpc, yet if some other application is installed that has a dependency on one (or both) of these libraries, it won't work, because it doesn't even know about SiriServer ... hence defying the whole purpose of a shared library ;-)

**Comment by gugahoi** [comment]
I see, but why would a single software care about "shared libraries"? I understand developers caring about them as they might have other things that require these libraries but the end user should not. I guarantee you most, if not all, of your applications use shared libraries like this. It makes it easier to manage them and to expand the software itself without going through major barriers and adding to the installations steps. 

As an example I give you Issue #156 - apparently it uses a python module called wordnik and it is not default in the user's system. How about we only have the plugin libraries, like jsonrpc and wordnik, included then? Wouldn't that make sense?

**Pull request closed without merging**
