### PR TITLE
Wolfram Alpha plugin new version

### PR DESCRIPTION
**Pull request by WebScript**
Hi!
This is new version of Wolfram Alpha plugin. Please delete the wolfram.py and add wolframSiri.py (or rename it if you want).
Thank you.

### CODE REVIEW

**Comment by janrueth** [comment]
Could you also please rename the file to the old name, such that there is no need to update the plugins.conf

```
  git rm 
  git mv
```

**Comment by WebScript** [comment]
It is renamed. Can you merge it? I am developer of this plugin and this is the newest version.

**Comment by piejanssens** [comment]
You could also just changes the content of the file to make your changes.

**Comment by radiotracker** [comment]
where can i find AnswerSnippet, AnswerObject, AnswerObjectLine? :P
thanks 4 help!

**Comment by WebScript** [comment]
Can somebody merge it?! I spent a lot of time on it...

**Comment by piejanssens** [comment]
Give it some time my friend. The only person with the rights to merge
you commits is Eicheurntjen and I think he's at work right now...

What has improved in your new version?

## 

Pieter Janssens

On 09 Feb 2012, at 21:12, WebScript
reply@reply.github.com
wrote:

**Pull request merged**
