### PR TITLE
XBMC plugin update (new feature + bug fix)

### PR DESCRIPTION
**Pull request by piejanssens**
BTW have you considered making it possible to run the SiriServer as a daemon?

I only have access to my server through SSH, as soon as I close the SSH connection the python script stops running.

### CODE REVIEW

**Comment by rbuckbailey** [comment]
I have posted a launchdaemon for the mac on this thread: https://github.com/Eichhoernchen/SiriServer/issues/109

I'm less familiar with building daemon files for linux so we may all be better off if I leave it to somebody else to do the translation.

**Comment by onetootreefor** [comment]
@tripkip you can run the python command in screen ... for example:
screen -S siri sudo python siriServer.py 

and then when you want to 'minimize' the screen just use key combo: ctrl+a+d 
to close: ctrl+c 
to recall a 'minimized' screen:screen -r siri (or whatever you named your screen)

**Comment by piejanssens** [comment]
@onetootreefor That's working great, thanks man!

Put that in the wiki ;-)

**Comment by ipadshouse** [comment]
I am using TeamViewer to start the server

**Comment by KasimAhmic** [comment]
What exactly are the requirements for this plugin? I noticed that in the code it has username and password so does that mean I need an account somewhere? Also, I noticed something about Apple TV.

**Comment by spang11ers** [comment]
Is the XMBC plugin for the cydia app or for the XMBC remote? Thanks

**Comment by piejanssens** [comment]
It's for XBMC itself, it acts as a remote. It can be used on any XBMC client (XBMC Live, Win, Unix)

**Comment by gugahoi** [comment]
@TheInfection @spang11ers the appletv.local is because when I developed it I was trying it on my XBMC AppleTV installation. This is related to the XBMC software itself and pretty much platform independent since XBMC can be installed on a multitude of OS's. You will have to edit the XBMC.py files with the information about your system as it says on the [wiki here on github](https://github.com/Eichhoernchen/SiriServer/wiki/Plugins)

By the way, good additions @tripkip !

Also, if you are on *buntu/debian based systems, I have whipped up an init.d script for siriserver, this way you can sart it at boot and in the background. I'll make a pull request for it....

**Comment by rbuckbailey** [comment]
@gugahol I put my Mac LaunchDaemon files in a "DaemonFiles" folder. We might want to keep start-up type files together in the same place. Don't mind whether it's DaemonFiles or StartupFiles or whathaveyou, but I figure it makes organizational sense to agree on a folder name.

@tripkip Sorry for hijacking the thread with an aside...

**Comment by gugahoi** [comment]
Perfect timing @autobuck I was about to make the commit. I'm not sure that is the best name for a init.d script folder as it is not only Daemon related since it converts the process into a service, however it would be annoying to have multiple folders with this kind of files so I'll put it in 'DaemonFiles' name for now...

**Comment by rbuckbailey** [comment]
You're right... if I hadn't already done the commit I'd change it to "startup files" or something of the like. We'll have to rename the folder later after they're merged.

**Comment by gugahoi** [comment]
@autobuck  done -> https://github.com/Eichhoernchen/SiriServer/pull/126

**Pull request merged**
