### PR TITLE
Switched to MySQL

### PR DESCRIPTION
**Pull request by jimmykane**
I like your project very much and i would like to contribute!

I think that switching to mysql is more siri friendly due to the fact that it stores assistants and also allow multiple assistant and database reading without locks. 

my email is jimmykane9@gmail.com and i would be happy to collaborate in this project.

### CODE REVIEW

**Comment by Ovanio** [comment]
I think we have to make it possible that both databases can be used.
I already changed Siri to MYSQL too. But i asked in chat and and some don't like MYSQL and think sqlite is the best solution.
Bye the way my MYSQL changes: https://github.com/Ovanio

If Eichhörnchen or/and the others want, I can pull it.

**Comment by Playfrog4u** [comment]
I get 

Traceback (most recent call last):
  File "siriServer.py", line 27, in <module>
    import db
  File "/root/Google-API/db.py", line 5, in <module>
    import MySQLdb as mdb
ImportError: No module named MySQLdb

**Comment by jimmykane** [comment]
Install MySQL python support.

**Comment by jimmykane** [comment]
Why not like MySQL ?

**Comment by Playfrog4u** [comment]
ok i am installing the MySQL python support. Thanks

**Comment by rbuckbailey** [comment]
I would definitely like to see MySQL support. How about a command-line toggle to merge the options?

**Comment by Playfrog4u** [comment]
sudo apt-get install python-mysqldb

**Comment by snxraven** [comment]
I deff love this, however there is a small issue when a new user that is in a diff timezone, language or region it updates everyone's:  timezone, language and region,

Example: http://grwh.net/error.PNG

I have moved to: Ovanio's git version because it stores data correctly

**Comment by jimmykane** [comment]
Will fix this asap

**Comment by Ovanio** [comment]
We have to make a standard how plugins can access the database. It doesn't makes sense if everyone (like me) are developing "something" for this reason. And I think we need more db transactions for plugins. With sqlite I had problems with 2 db requests at the same time (for example: plugin takes the connection and creates a cursor, at the same time the main siriServer makes a db update).
Maybe it is possible to make it working with both (if there are users who don't like mysql). Nevertheless I don't know if this is "important" and "easy" possible.
I need the database. 
First: All my smaltalk is in this database (plugin dbTalk). I imported an german AIML file with many questions and answers. I don't like the idea of writing these q/a's in a plugin file. 
Second: I have the possibility to create a new question/answer by saying: new answer to the last question; or similar question.

**Comment by jimmykane** [comment]
Fixed in latest update in my fork

**Comment by Playfrog4u** [comment]
It dont work.

**Comment by snxraven** [comment]
I am using it and have over 100 users its working :P

**Comment by Playfrog4u** [comment]
Are you using jimmys

**Comment by snxraven** [comment]
Yes, moved to it this morning, siri.grwh.net

**Comment by jimmykane** [comment]
Glad to hear about that @snxraven ! Making more changes and implementing user recognition + all apple smaltalk replies!

**Comment by Playfrog4u** [comment]
Ok got it to work. Thanks

**Comment by snxraven** [comment]
@jimmykane I do have an issue that pops up about once a day: 

http://grwh.net/error.PNG

Not sure how to fix it

**Pull request closed without merging**
