### PR TITLE
fixed utf-8 in german, and added some commands in german!

### PR DESCRIPTION
**Pull request by ghost**
:-)

### CODE REVIEW

**Comment by Jerrot** [comment]
Well, I don't think it's very useful over time if everyone adds his own favorite answers to the same plug-ins and even removes others. 

I'd prefer some basic logical attempt directed by Eichhörnchen for that, like filling these basic plug-ins with the original Siri answers only and either including some additional script with user-defined stuff or just separate plug-ins that won't be merged into the basic ones. This might be some approach for all other basic plug-ins, too.

(Plus - I don't want my iPhone to answer me "Servus". Really! ;-) )

**Comment by DerPeiler** [comment]
Jerrot, whois the like button? ;-)

**Comment by ghost** [comment]
John-DEV das ist nicht falsch ;) es geht perfekt.

**Comment by YoSev** [comment]
Klar geht es.. dann geh mal auf leo.org und übersertz das wort "handy"..
Oder setz das Plugin auf erste stelle und sag okay siri, where am i.. wird lustig!

**Comment by ghost** [comment]
jojo passt schon bin noch n anfänger ;))

**Pull request closed without merging**
