### PR TITLE
 The Cydia packages MyAssistant and AssistantExtensions work but only if...

### PR DESCRIPTION
**Pull request by YoSev**
... the first letter is a

Issue #96

### CODE REVIEW

**Comment by rippedwarrior** [comment]
I have AssistantExtensions installed on my iPhone 4 running Spire, but AE isn't working with Siri Server at all.  I've even checked to make sure the change made above is changed on my server.  Siri just keeps saying, "Sorry, I don't understand (whatever)" whenever I try to use a command from AE.  Is there a way to make it work?

**Comment by onetootreefor** [comment]
same here although MyAssistant seems to be working better, but if you try to launch a app from siri via MyAssistant SB crashes. Other than that it works, but AssistantExtensions doesn't work at all for me.

update from cydia fixed MyAssistant

**Comment by m404** [comment]
i noticed that it's the opposite for AssistantExtensions ?
it doesn't work when u say, as an example, "Let's chat" ... it will answer that it doesn't understand it ... now make it a manual input (tap on the "Let's chat"), change the first letter to be lowercase so it looks like "let's chat", and it'll load up alice ... what's up with that ?

**Comment by ismaGNU** [comment]
@m404 The same happens to me. AssistantExtension is working, but I have to use it with manual input. As you said, It behaves in the opposite way as SiriServer does :D. 
I can chat perfectly, by manual way I put "let's chat", and then AE understand everything and replies you. So It is so weird these behaviour.

Anyone?

**Pull request merged**
