### PR TITLE
Yelp, Google Places, Yahoo Local Search, apikeys.conf rename, and so much more

### PR DESCRIPTION
**Pull request by apexad**
I've created a Yelp, Googke Places, and Yahoo Local Search plugin that uses:
find | show | where (the, me a, is, etc...) nearby | nearest | closest business/ restraurant

apikeys.conf renamed with -sample

some fixed grammar
french added in many places
has the twitter plugin mergerd
has translation plugin merged
has a chuck norris facts (english) plugin
has an imdbapi movie info and poster plugin
...and so much more

### CODE REVIEW

**Comment by jimmykane** [comment]
Nice!

**Comment by WebScript** [comment]
Good work. But I will be using my version. :)

**Comment by jimmykane** [comment]
@webscript your version doesnt support multiple client connection

**Comment by apexad** [comment]
@jimmykane seems you figured out the issue with Google Places?  as you deleted the comment about it crashing to safe mode.  I was going to tell you many people are saying it's all working.  

It does require the last commit by Eichhoernchen as the last thing he did was add the localSearch plugin

Otherwise, see this forum post... http://hack.silentspark.net/phpbb/viewtopic.php?f=29&t=95#p367 I did a really good write up on usage and URL adjustment

**Comment by jimmykane** [comment]
Yes google places works ok even for greece even though Greece is not listed. Also please look at my fork for the multiyser support with SQLite. 

Now the server only does one connection to the db thus avoiding server load and file locks.

**Comment by WebScript** [comment]
To jimmykane: You did not see my places version and my server edit with UDID controlling. I only released Wolfram Alpha plugin that works well. And my places script works well with 20 and more people online, too.
PS: I can ´t show how can I did UDID auth because it is still in dev and I spent a lot of time on learning some know how about programming for Siri. I am sorry.

**Comment by jimmykane** [comment]
The udid is made how. I have made auth via iCloud id! 
How do you grab udid if it's not send?

**Comment by apexad** [comment]
@jimmykane I'm not concerned at all about 'multi-user' support to my Siri Server as I'm completely happy to release my code and plugins but have no desires for anyone but me to connect to my actual Server.

So many other things are more important

**Comment by WebScript** [comment]
jimmykane: Some kind of iOS programming and editing server. As I said I can ´t show anything.

**Comment by jimmykane** [comment]
@apexad yes the plugins etc is no1 priority. But I don't agree with you on the multiuser support. 
If you where right (in my humble opinion) then every person on the world that wanted to use spire with google API would have to know Linux, have static ip, and setup his own server. 
Not cool at all. It misses the point of the siriserver. You could just name the project then as google socket not server.

**Comment by jimmykane** [comment]
@webscript so it needs a package from cydia. Yes this way has been done before.

**Comment by WebScript** [comment]
Yes, but never released with source and working version with mysql support and much more ;)

**Comment by apexad** [comment]
**@jimmmykane**    don't mis-understand.  I understand the need for multi-user support to be present in the main github repo, but I forked the repo for my own benefit, not anyone else's.

I'm humbled and encouraged that people will use my plugins in their forks and on their servers.  I will always push any code I write to github. It's up to other developers out there to modify it for themselves, or the masses as they see fit.

However, the underlying goal of my fork is and will always be so that I have Siri on my iPhone 4 and to share what my Siri Server looks like with the world.  So, I have no need to take the time to merge in a github repo that has mult-user support.  At the very least, it's low on my priority list.

**Comment by MahmoudM10** [comment]
Hi @apexad,
How Can I add this to my server ?! .. there's many commits .. I'm new for this .. I was adding  just by copy & paste ..

Thanks :)

**Comment by apexad** [comment]
I have no desire to teach anyone how to use git/github, as their help documents are more than adequate.  However, you can use the zip file method:

https://github.com/apexad/SiriServer/zipball/master

Also, remember to add any plugin to plugins.conf and check for needed API Keys at the top of any plugin that will need to be defined in apiKeys.conf

**Comment by jimmykane** [comment]
@apexad point taken 

@webscript @apexad 

The only confusions ATM is that there are many plugin versions, many SQL support version etc. 

This creates a chaos. The best solution is for everyone to focus on the best point to develop and have a common source. 

Eg @apexad you are very good with the plugins and @webscript you will develop the auth, so better eg is only one to merge plugins etc.
If you get me.

**Comment by WebScript** [comment]
Jimmykane, can I use your The-Three-Little-Pigs-Siri-Proxy design for my BIG project? I want to code some feedback page with administration. I am PHP programmer for about 4 years and I am making my own cPanel for GameHost.
P.S. I am plugin dev, too. I have developed as first Wolfram Alpha, GPlaces with listings and now I am working on Calendar. But I am not releasing it because there is people who have SMS plugin and he does not want to release it.

**Comment by snxraven** [comment]
@WebScript Who cares who has what? to be honest it is kind of childish to keep code because someone isnt releasing theirs yet...

**Comment by WebScript** [comment]
snxraven Are you people who have SMS plugin? Because some people with familiar nick name to yours have SMS plugin and don't want to share it.

**Comment by snxraven** [comment]
I do not have the plugin. 

Jonathon Nickols
[Technical Director]
GreenRiverWebHosts
Tech Line: (805) 694-8277
http://grwh.net

**Comment by jimmykane** [comment]
@apexad added most of the plugins to my github

**Comment by praetorians** [comment]
@jimmykane, i tried to create a new server using yours mysql version.
but i get an error. 

file siriserver.py line 29 in <module>
importerror: no module named mysql.cursors

**Comment by jimmykane** [comment]
Thanks for the info! Will fix when I wake up.

**Comment by jimmykane** [comment]
@praetorians  issue fixed but please move this conversation at my pull request!

**Comment by praetorians** [comment]
okay.
will post the next issue related to you on your pull request.
tyvm.

**Comment by janrueth** [comment]
Uff... looks like a lot of code to review...

**Comment by chenr1** [comment]
You Rock!!! I can't wait to add this. How long did this take you?

**Comment by danzatt** [comment]
@jimmykane 
You wrote that you've made auth via iCloud ID, it's required to install .deb package ? It's in your fork or it's still in development ? If it is in your fork, how can I use it ? Thanks

**Comment by WebScript** [comment]
Paradox: You are not able to sell capacity on your server, so you won't
need it. And I think it can be crackable by logging into the same iCloud in
other devices or special deb ;) 2 or 3 hours publicity and there will be
some crack deb. My iOS dev edited Siri's protocol in minutes and can edit
everything that is send by Siri.
By the way: Jimmykane has this auth in his The-Three-Little-Pigs-Siri-Proxy
in dev section. It is SiriProxy in ruby.

2012/3/4 P4r4doX <
reply@reply.github.com

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
