### PR TITLE
Update plugins/smalltalk.py Random Answer

### PR DESCRIPTION
**Pull request by Mikesn**

### CODE REVIEW

**Comment by ghost** [comment]
super arbeit! warte ich behebe noch schnell die ö ä ü probleme... dann passt alles! :)

**Comment by onetootreefor** [comment]
i have added some responses and added some inputs, but i don't speak german, are you available to get on IRC so i can send you some code?

**Comment by ghost** [comment]
i can help you too ;D they are some umlaute(ö ä ü) problems.

**Comment by janrueth** [comment]
sorry this repo is not maintained anymore, no pulls

**Pull request closed without merging**
