### PR TITLE
Web searching using voice: "Web search", "web", "internet search", "internet"; in german too.

### PR DESCRIPTION
**Pull request by ghost**
Hopefully everything is correct.

### CODE REVIEW

**Comment by ghost** [comment]
What?

plugins/wwwsearch.py

**Comment by janrueth** [comment]
It has no content

**Comment by ghost** [comment]
Now it should be ok.

**Comment by YoSev** [comment]
If you don't want siri to read "web search..", line 13 doesn't work, line 15 doesn't work

**Comment by YoSev** [comment]
add a space between ' ', else the speek text will be replaced with the read text..

**Comment by ghost** [comment]
Should I remove speech = speech.strip()?

Sorry, I am new to most of this.

**Comment by ghost** [comment]
Ok? Or not?

**Comment by ghost** [comment]
works perfekt :) can you write it in german too? 
websearch in german= websuche or web suche. internet = internet

**Comment by ghost** [comment]
German now works.

Please correct any incorrect grammar.

**Comment by DerPeiler** [comment]
if speech == "":
                speech = self.ask("nach was soll ich suchen?")

Hi, 

sounds a little bit better in german. 

ty!

**Comment by DerPeiler** [comment]
tested now the plugin and get a invalid syntax on line 8... i'm confused about, i don't see any different to a other plugin.

**Comment by praetorians** [comment]
tested. working find. nice share.

**Comment by ghost** [comment]
Line 8 is blank...

**Comment by DerPeiler** [comment]
i know what you mean, line 8 is empty... but i get this error :-) don't know why, coy paste for serval times from your git but nothing changed... :-( 

Traceback (most recent call last):
  File "/home/th/app/siri/otp/siriserver/PluginManager.py", line 25, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/home/th/app/siri/otp/siriserver/plugins/wwwsearch.py", line 8
         
     ^
 SyntaxError: invalid syntax

**Comment by ghost** [comment]
What is in your wwwsearch.py?

Thanks.

**Comment by WebScript** [comment]
Why when I say Web search Bora Bora it does not do anything? Only shows that it recognizes speech and nothing do.

**Comment by ghost** [comment]
Did you unlock your device?

It works for me.

**Comment by ghost** [comment]
By unlock i mean, "slide open to unlock"

**Comment by ghost** [comment]
Works?

**Pull request merged**
