### PR TITLE
updated smalltalk.py

### PR DESCRIPTION
**Pull request by onetootreefor**
added 50+ new commands, cleaned up existing smalltalk.
working on adding more.

### CODE REVIEW

**Comment by onetootreefor** [comment]
edit: fixed code ok to pull!

**Comment by bidluo** [comment]
Should I start fixing it for other English languages? Like en_AU

**Comment by onetootreefor** [comment]
you can if you like ill be out of town for roughly 36 hours so i can't begin working until i get home.

**Comment by janrueth** [comment]
could it be that you saved the file with the wrong encoding? I only get funny characters where german umlaute should be when viewing the diff

**Comment by onetootreefor** [comment]
yes i think it was cus i saved it in a weird text editor first, but i fixed the issue and you can pull it...all german charactrers in the latest pull request show up, and work.

**Comment by markhack** [comment]
https://github.com/Eichhoernchen/SiriServer/issues/223

**Pull request merged**
