### PR TITLE
sometimes google times out or does not respond in time. especially annoy...

### PR DESCRIPTION
**Pull request by seabass86**
...ing while in a plugin as it cancels all requests and sometimes you get stuck at a ask() method... this fixed the issue for me

### CODE REVIEW

**Comment by janrueth** [comment]
If it times out thats fine I think, I think the issue is, that if it times out, the plugin should be killed. However this is difficult as it is generally not possible to kill a foreign thread, maybe we could add after the synchronization methods checks to kill plugin if no data could be gathered

**Comment by YoSev** [comment]
how can a plugin be loaded without a matching google result? there should be no regex match..
or don't you mean the "normal" plugins..?

**Comment by seabass86** [comment]
not the plugin causes the time out... following scenarion. I am using my sms plugin. it recognizes sent sms , the asks for contact...etc, then at the ask method for the message google does not respond in time ant the exception is thrown, the plugin gets stuck or canceled. now with this is tries it to send the recorded speech to google 2 more times. and if all three times time out as google does not respond sends back that there was no connection to google. made my server 100 times more reliable now, not a single time did i get the issue of no connection to google...

**Comment by seabass86** [comment]
so the issue is not the plugin but the time that google does not respond... also happens sometimes when you just started a siri request with no plugin running. solved also that. i did a test, from 20 connections google answered 16 in time, the other 4 where managed to go through the 2nd time

**Comment by seabass86** [comment]
not right now, as there is no connection between siri and that app... maybe somebody on cydia will provide something soon

**Comment by seabass86** [comment]
will integrate google voice though....

**Comment by janrueth** [comment]
I don't like the solution here... 

a: loops were invented to use them
b: this should be done differently... there should be a callback to the plugin telling it to wait some more time if first google answer failed...
c: I still need to figure out a good way to kill a plugin incase iPhone cancels request or google won't respond...

**Comment by seabass86** [comment]
well it's not just timing out but sometimes google just does not respond

**Comment by iPhoneV8** [comment]
sending flac to google.......
no connection to google possible....

after changing the time out 3 to 6 it work for me too...but very slow respond :)

Thanks's

**Pull request closed without merging**
