### PR TITLE
Xbmc plugin

### PR DESCRIPTION
**Pull request by gugahoi**
Plugin to control XBMC from Siri.

Commands that are accepted at the moment are:

xbmc play/pause -> plays/pauses current video
xbmc stop -> stops current video
xbmc play [movie name] -> starts playing the movie if a match was found, if multiple matches found than it returns them through Siri
xbmc info -> returns the XBMC URL being used
xbmc shutdown/shut down/turn off -> Shuts down computer through XBMC's internal functions
xbmc start/boot/boot up -> send a magic packet to wake up the computer.

### CODE REVIEW

**Comment by gugahoi** [comment]
I could use some help with some regex's if anyone feels like contributing. Although it seems to work ok at the moment.

**Comment by 128keaton** [comment]
oi wow! Sweet! I just dont have XBMC! Maybe we can get this so work with AppleTV. Ill bet more people will use that.

**Comment by gugahoi** [comment]
We can certainly try another plugin for AppleTV, just don't know how feasible it is. XBMC has it's own JSONRPC server so it is very straight forward to interact with it.

**Comment by gugahoi** [comment]
Also, you will notice i didn't use regexes cause I was struggling with them but if you know how to apply them to these commands, please feel free! I really think regexes are the way to do it but need to read up on them...

**Pull request merged**
