### PR TITLE
Update plugins/smalltalk.py

### PR DESCRIPTION
**Pull request by Mikesn**
Deutsche Übersetzung zu den englischen Ergänzungen
German translation for the added parts

### CODE REVIEW

**Comment by ghost** [comment]
du hast bei vielen fragen die klammern vergessen :D

**Comment by Mikesn** [comment]
OK, bin schon sehr müde, wo z.B. hab ich denn die Klammern vergessen?

**Comment by ghost** [comment]
bei allen englischen :D

**Comment by onetootreefor** [comment]
thanks for adding the german as I only speak english.

question, why did you remove the "am i fat" and "thanks for..." responses all together instead of just adding the German?

**Comment by janrueth** [comment]
Also closing this pull request. The plugin should be rewritten to be able to choose randomly from a lists of answers specific to a certain question type

**Pull request closed without merging**
