### PR TITLE
Added Mysql Support and User data capture+ linking to assistants

### PR DESCRIPTION
**Pull request by jimmykane**
Fixed an issue where all assistantid's where generated by the same uuid4 
Added mysql support instead of sqlite due to file locks and server runtime breakage
Added user firstname and nickname capture
Fixed the issue where a device was not setup (region,etc)

### CODE REVIEW

**Comment by ghost** [comment]
can you do a example?

self.say(u"Hello, {0}.".format(self.user.firstName.decode("utf-8")))

doesn't work

**Comment by jimmykane** [comment]
It works.

**Comment by ghost** [comment]
no i've always get: AttributeError: 'smalltalk' object has no attribute 'user'

**Comment by jimmykane** [comment]
Wait for new release. All will be fixed. That's why I closed the pull

**Pull request closed without merging**
